# Generated by tools/update_artifact_registry.py.
# Do not edit manually.
#
# Embedded hashes keep artifact verification compatible with freezers and zip imports.
# They become trusted only after this generated file is reviewed and committed.

# Source: https://github.com/prefix-dev/pixi/releases/tag/v0.48.2
PIXI_VERSION = "v0.48.2"
PIXI_SHA256 = {
    "pixi-aarch64-apple-darwin.tar.gz": "ed426d19a0dd9f9933837825948ddd8bad9dbff1e4a4424ad44cf51f7be2edf1",
    "pixi-aarch64-pc-windows-msvc.zip": "10f7db54662d5452ff4c543793d79de5014b96711c69ea448de86bbd17d62616",
    "pixi-aarch64-unknown-linux-musl.tar.gz": "403235fa576410165235733a316c764f66175593bef4b1e9233dabfdc34d6bf3",
    "pixi-x86_64-apple-darwin.tar.gz": "14d5ea0383e52cf8caac43586c0ec9c709263a765365d6897a8d111ea27d6e2e",
    "pixi-x86_64-pc-windows-msvc.zip": "1d91033aeab21c83538f34aa6288aa862d55a32e0d45aa6a4dd9f89c7e0ddb92",
    "pixi-x86_64-unknown-linux-musl.tar.gz": "6c7d338892c54a5d45d241a11ec0e563104325fcec3d19cde483366f87b88692",
}

# Source: https://github.com/mamba-org/micromamba-releases/releases/tag/2.3.0-1
MICROMAMBA_VERSION = "2.3.0-1"
MICROMAMBA_SHA256 = {
    "micromamba-linux-64": "83f38b81295dade6b242b40dbab81bcd9fb03bb196928ab15f552cbafe82386b",
    "micromamba-linux-aarch64": "ca8af1dcf82059612d0dc110de3e875d107e6e77a6e77578b0ffeb74bfc2c2eb",
    "micromamba-linux-ppc64le": "65f596573e531694d24b41968458fd347dbd3b3b7f59ba0095ade911b8b599b4",
    "micromamba-osx-64": "1aac2a0c345c4ee441040a07784c5b6ed432738fa4500b15cb1e758870205320",
    "micromamba-osx-arm64": "b2f8c1756d20ac5dadd40a822761b6940e7685ab53e1a09d83ece38fbb366209",
    "micromamba-win-64": "7033f20918a00f490b2d6d493738d2b8552fcb0f7fb2eab06a6b191bd7a33477",
}

# Source: Microsoft Visual C++ Redistributable for Visual Studio 2015-2022.
VC_REDIST_ARTIFACT_NAME = "VC_redist.x64.exe"
VC_REDIST_URL = "https://download.visualstudio.microsoft.com/download/pr/7ebf5fdb-36dc-4145-b0a0-90d3d5990a61/CC0FF0EB1DC3F5188AE6300FAEF32BF5BEEBA4BDD6E8E445A9184072096B713B/VC_redist.x64.exe"
VC_REDIST_SHA256 = "cc0ff0eb1dc3f5188ae6300faef32bf5beeba4bdd6e8e445a9184072096b713b"
