# Generated by tools/update_artifact_registry.py.
# Do not edit manually.
#
# Embedded hashes keep artifact verification compatible with freezers and zip imports.
# They become trusted only after this generated file is reviewed and committed.

# Source: https://github.com/prefix-dev/pixi/releases/tag/v0.73.0
PIXI_VERSION = "v0.73.0"
PIXI_SHA256 = {
    "pixi-aarch64-apple-darwin.tar.gz": "63e7cc91ef10eda71765c42e951362a084b2cbcbc93fb55c375c4f3acbfd7d00",
    "pixi-aarch64-pc-windows-msvc.zip": "0ed95db2387984cc8a03aaceb7e493bb43a78cd901ef977e2bdbc2e641e491dd",
    "pixi-aarch64-unknown-linux-musl.tar.gz": "0788f47eb37e0706de209c3ce81cc804ee128f7dd4ec09a686754a67170ddb64",
    "pixi-x86_64-apple-darwin.tar.gz": "0c89d86eb3adc35773e3b00f443b68edcfcdd7b61700282d712613bcaf797f61",
    "pixi-x86_64-pc-windows-msvc.zip": "d9044186bfea9771b8e35b0ed032352b557a82528cd5165db6b8ad137c7a873c",
    "pixi-x86_64-unknown-linux-musl.tar.gz": "682564e7cd35d38307df3cd6c8e9a45a1437d20febac0c8d165809d7c38408d1",
}
